// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: loboscontrol.proto

#include "loboscontrol.pb.h"
#include "loboscontrol.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace loboscontrol {

static const char* ControlPlane_method_names[] = {
  "/loboscontrol.ControlPlane/AddUser",
  "/loboscontrol.ControlPlane/ListAllUsers",
  "/loboscontrol.ControlPlane/ListUser",
};

std::unique_ptr< ControlPlane::Stub> ControlPlane::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< ControlPlane::Stub> stub(new ControlPlane::Stub(channel, options));
  return stub;
}

ControlPlane::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_AddUser_(ControlPlane_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListAllUsers_(ControlPlane_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListUser_(ControlPlane_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status ControlPlane::Stub::AddUser(::grpc::ClientContext* context, const ::loboscontrol::AuthParams& request, ::loboscontrol::UserReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loboscontrol::AuthParams, ::loboscontrol::UserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_AddUser_, context, request, response);
}

void ControlPlane::Stub::async::AddUser(::grpc::ClientContext* context, const ::loboscontrol::AuthParams* request, ::loboscontrol::UserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loboscontrol::AuthParams, ::loboscontrol::UserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddUser_, context, request, response, std::move(f));
}

void ControlPlane::Stub::async::AddUser(::grpc::ClientContext* context, const ::loboscontrol::AuthParams* request, ::loboscontrol::UserReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_AddUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>* ControlPlane::Stub::PrepareAsyncAddUserRaw(::grpc::ClientContext* context, const ::loboscontrol::AuthParams& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loboscontrol::UserReply, ::loboscontrol::AuthParams, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_AddUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>* ControlPlane::Stub::AsyncAddUserRaw(::grpc::ClientContext* context, const ::loboscontrol::AuthParams& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControlPlane::Stub::ListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::loboscontrol::ListAllUsersReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loboscontrol::Filters, ::loboscontrol::ListAllUsersReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListAllUsers_, context, request, response);
}

void ControlPlane::Stub::async::ListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters* request, ::loboscontrol::ListAllUsersReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loboscontrol::Filters, ::loboscontrol::ListAllUsersReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAllUsers_, context, request, response, std::move(f));
}

void ControlPlane::Stub::async::ListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters* request, ::loboscontrol::ListAllUsersReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListAllUsers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loboscontrol::ListAllUsersReply>* ControlPlane::Stub::PrepareAsyncListAllUsersRaw(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loboscontrol::ListAllUsersReply, ::loboscontrol::Filters, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListAllUsers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loboscontrol::ListAllUsersReply>* ControlPlane::Stub::AsyncListAllUsersRaw(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListAllUsersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status ControlPlane::Stub::ListUser(::grpc::ClientContext* context, const ::loboscontrol::Key& request, ::loboscontrol::UserReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::loboscontrol::Key, ::loboscontrol::UserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListUser_, context, request, response);
}

void ControlPlane::Stub::async::ListUser(::grpc::ClientContext* context, const ::loboscontrol::Key* request, ::loboscontrol::UserReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::loboscontrol::Key, ::loboscontrol::UserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListUser_, context, request, response, std::move(f));
}

void ControlPlane::Stub::async::ListUser(::grpc::ClientContext* context, const ::loboscontrol::Key* request, ::loboscontrol::UserReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListUser_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>* ControlPlane::Stub::PrepareAsyncListUserRaw(::grpc::ClientContext* context, const ::loboscontrol::Key& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::loboscontrol::UserReply, ::loboscontrol::Key, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListUser_, context, request);
}

::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>* ControlPlane::Stub::AsyncListUserRaw(::grpc::ClientContext* context, const ::loboscontrol::Key& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListUserRaw(context, request, cq);
  result->StartCall();
  return result;
}

ControlPlane::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlPlane_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlPlane::Service, ::loboscontrol::AuthParams, ::loboscontrol::UserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlPlane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loboscontrol::AuthParams* req,
             ::loboscontrol::UserReply* resp) {
               return service->AddUser(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlPlane_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlPlane::Service, ::loboscontrol::Filters, ::loboscontrol::ListAllUsersReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlPlane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loboscontrol::Filters* req,
             ::loboscontrol::ListAllUsersReply* resp) {
               return service->ListAllUsers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      ControlPlane_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< ControlPlane::Service, ::loboscontrol::Key, ::loboscontrol::UserReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](ControlPlane::Service* service,
             ::grpc::ServerContext* ctx,
             const ::loboscontrol::Key* req,
             ::loboscontrol::UserReply* resp) {
               return service->ListUser(ctx, req, resp);
             }, this)));
}

ControlPlane::Service::~Service() {
}

::grpc::Status ControlPlane::Service::AddUser(::grpc::ServerContext* context, const ::loboscontrol::AuthParams* request, ::loboscontrol::UserReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControlPlane::Service::ListAllUsers(::grpc::ServerContext* context, const ::loboscontrol::Filters* request, ::loboscontrol::ListAllUsersReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status ControlPlane::Service::ListUser(::grpc::ServerContext* context, const ::loboscontrol::Key* request, ::loboscontrol::UserReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace loboscontrol

