syntax = "proto3";

package loboscontrol;

option go_package = "lobos/controlplane";

// ControlPlan implements the control plane for Lobos
service ControlPlane {

    // S3 User management
    // Add user adds an S3 user
    rpc AddUser (User) returns (UserReply) {}
    // ListAllUsers returns a list of all S3 users
    rpc ListAllUsers (Filters) returns (ListAllUsersReply) {}
    // ListUser lists all user's infos
    rpc ListUser(Name) returns (UserReply) {}
    // Etc
}

message User {
  string name = 1;
  string key = 2;
  string secret = 3;
  string backend = 4;
}

message Filters {
    string message = 1;
}

message Name {
    string name = 1;
}

message ListAllUsersReply {
    repeated UserReply users = 1;
}

message UserReply {
    User user = 1;
}