// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: loboscontrol.proto
#ifndef GRPC_loboscontrol_2eproto__INCLUDED
#define GRPC_loboscontrol_2eproto__INCLUDED

#include "loboscontrol.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace loboscontrol {

// ControlPlan implements the control plane for Lobos
class ControlPlane final {
 public:
  static constexpr char const* service_full_name() {
    return "loboscontrol.ControlPlane";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // S3 User management
    // Add user adds an S3 user
    virtual ::grpc::Status AddUser(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::loboscontrol::UserReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>> AsyncAddUser(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>>(AsyncAddUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>> PrepareAsyncAddUser(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>>(PrepareAsyncAddUserRaw(context, request, cq));
    }
    // ListAllUsers returns a list of all S3 users
    virtual ::grpc::Status ListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::loboscontrol::ListAllUsersReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::ListAllUsersReply>> AsyncListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::ListAllUsersReply>>(AsyncListAllUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::ListAllUsersReply>> PrepareAsyncListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::ListAllUsersReply>>(PrepareAsyncListAllUsersRaw(context, request, cq));
    }
    // RmUser removes an user
    virtual ::grpc::Status RmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::google::protobuf::BoolValue* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> AsyncRmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(AsyncRmUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> PrepareAsyncRmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(PrepareAsyncRmUserRaw(context, request, cq));
    }
    // AddKey adds a key to specified user
    virtual ::grpc::Status AddKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::loboscontrol::UserReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>> AsyncAddKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>>(AsyncAddKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>> PrepareAsyncAddKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>>(PrepareAsyncAddKeyRaw(context, request, cq));
    }
    // RmKey removes a key from a specified user
    virtual ::grpc::Status RmKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::google::protobuf::BoolValue* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> AsyncRmKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(AsyncRmKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>> PrepareAsyncRmKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>>(PrepareAsyncRmKeyRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      // S3 User management
      // Add user adds an S3 user
      virtual void AddUser(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddUser(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // ListAllUsers returns a list of all S3 users
      virtual void ListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters* request, ::loboscontrol::ListAllUsersReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void ListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters* request, ::loboscontrol::ListAllUsersReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // RmUser removes an user
      virtual void RmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // AddKey adds a key to specified user
      virtual void AddKey(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response, std::function<void(::grpc::Status)>) = 0;
      virtual void AddKey(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      // RmKey removes a key from a specified user
      virtual void RmKey(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RmKey(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>* AsyncAddUserRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>* PrepareAsyncAddUserRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::ListAllUsersReply>* AsyncListAllUsersRaw(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::ListAllUsersReply>* PrepareAsyncListAllUsersRaw(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* AsyncRmUserRaw(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* PrepareAsyncRmUserRaw(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>* AsyncAddKeyRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::loboscontrol::UserReply>* PrepareAsyncAddKeyRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* AsyncRmKeyRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::google::protobuf::BoolValue>* PrepareAsyncRmKeyRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status AddUser(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::loboscontrol::UserReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>> AsyncAddUser(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>>(AsyncAddUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>> PrepareAsyncAddUser(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>>(PrepareAsyncAddUserRaw(context, request, cq));
    }
    ::grpc::Status ListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::loboscontrol::ListAllUsersReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::ListAllUsersReply>> AsyncListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::ListAllUsersReply>>(AsyncListAllUsersRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::ListAllUsersReply>> PrepareAsyncListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::ListAllUsersReply>>(PrepareAsyncListAllUsersRaw(context, request, cq));
    }
    ::grpc::Status RmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::google::protobuf::BoolValue* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> AsyncRmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(AsyncRmUserRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> PrepareAsyncRmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(PrepareAsyncRmUserRaw(context, request, cq));
    }
    ::grpc::Status AddKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::loboscontrol::UserReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>> AsyncAddKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>>(AsyncAddKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>> PrepareAsyncAddKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>>(PrepareAsyncAddKeyRaw(context, request, cq));
    }
    ::grpc::Status RmKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::google::protobuf::BoolValue* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> AsyncRmKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(AsyncRmKeyRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>> PrepareAsyncRmKey(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>>(PrepareAsyncRmKeyRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void AddUser(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response, std::function<void(::grpc::Status)>) override;
      void AddUser(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void ListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters* request, ::loboscontrol::ListAllUsersReply* response, std::function<void(::grpc::Status)>) override;
      void ListAllUsers(::grpc::ClientContext* context, const ::loboscontrol::Filters* request, ::loboscontrol::ListAllUsersReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) override;
      void RmUser(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) override;
      void AddKey(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response, std::function<void(::grpc::Status)>) override;
      void AddKey(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RmKey(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::google::protobuf::BoolValue* response, std::function<void(::grpc::Status)>) override;
      void RmKey(::grpc::ClientContext* context, const ::loboscontrol::User* request, ::google::protobuf::BoolValue* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>* AsyncAddUserRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>* PrepareAsyncAddUserRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::loboscontrol::ListAllUsersReply>* AsyncListAllUsersRaw(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::loboscontrol::ListAllUsersReply>* PrepareAsyncListAllUsersRaw(::grpc::ClientContext* context, const ::loboscontrol::Filters& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* AsyncRmUserRaw(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* PrepareAsyncRmUserRaw(::grpc::ClientContext* context, const ::loboscontrol::RmUserParams& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>* AsyncAddKeyRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::loboscontrol::UserReply>* PrepareAsyncAddKeyRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* AsyncRmKeyRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::google::protobuf::BoolValue>* PrepareAsyncRmKeyRaw(::grpc::ClientContext* context, const ::loboscontrol::User& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_AddUser_;
    const ::grpc::internal::RpcMethod rpcmethod_ListAllUsers_;
    const ::grpc::internal::RpcMethod rpcmethod_RmUser_;
    const ::grpc::internal::RpcMethod rpcmethod_AddKey_;
    const ::grpc::internal::RpcMethod rpcmethod_RmKey_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // S3 User management
    // Add user adds an S3 user
    virtual ::grpc::Status AddUser(::grpc::ServerContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response);
    // ListAllUsers returns a list of all S3 users
    virtual ::grpc::Status ListAllUsers(::grpc::ServerContext* context, const ::loboscontrol::Filters* request, ::loboscontrol::ListAllUsersReply* response);
    // RmUser removes an user
    virtual ::grpc::Status RmUser(::grpc::ServerContext* context, const ::loboscontrol::RmUserParams* request, ::google::protobuf::BoolValue* response);
    // AddKey adds a key to specified user
    virtual ::grpc::Status AddKey(::grpc::ServerContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response);
    // RmKey removes a key from a specified user
    virtual ::grpc::Status RmKey(::grpc::ServerContext* context, const ::loboscontrol::User* request, ::google::protobuf::BoolValue* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddUser() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddUser(::grpc::ServerContext* context, ::loboscontrol::User* request, ::grpc::ServerAsyncResponseWriter< ::loboscontrol::UserReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_ListAllUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_ListAllUsers() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_ListAllUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllUsers(::grpc::ServerContext* /*context*/, const ::loboscontrol::Filters* /*request*/, ::loboscontrol::ListAllUsersReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListAllUsers(::grpc::ServerContext* context, ::loboscontrol::Filters* request, ::grpc::ServerAsyncResponseWriter< ::loboscontrol::ListAllUsersReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RmUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RmUser() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_RmUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::RmUserParams* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRmUser(::grpc::ServerContext* context, ::loboscontrol::RmUserParams* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::BoolValue>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_AddKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_AddKey() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_AddKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddKey(::grpc::ServerContext* context, ::loboscontrol::User* request, ::grpc::ServerAsyncResponseWriter< ::loboscontrol::UserReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RmKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RmKey() {
      ::grpc::Service::MarkMethodAsync(4);
    }
    ~WithAsyncMethod_RmKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRmKey(::grpc::ServerContext* context, ::loboscontrol::User* request, ::grpc::ServerAsyncResponseWriter< ::google::protobuf::BoolValue>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_AddUser<WithAsyncMethod_ListAllUsers<WithAsyncMethod_RmUser<WithAsyncMethod_AddKey<WithAsyncMethod_RmKey<Service > > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddUser() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::loboscontrol::User, ::loboscontrol::UserReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response) { return this->AddUser(context, request, response); }));}
    void SetMessageAllocatorFor_AddUser(
        ::grpc::MessageAllocator< ::loboscontrol::User, ::loboscontrol::UserReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::loboscontrol::User, ::loboscontrol::UserReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddUser(
      ::grpc::CallbackServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_ListAllUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_ListAllUsers() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::loboscontrol::Filters, ::loboscontrol::ListAllUsersReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::loboscontrol::Filters* request, ::loboscontrol::ListAllUsersReply* response) { return this->ListAllUsers(context, request, response); }));}
    void SetMessageAllocatorFor_ListAllUsers(
        ::grpc::MessageAllocator< ::loboscontrol::Filters, ::loboscontrol::ListAllUsersReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::loboscontrol::Filters, ::loboscontrol::ListAllUsersReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_ListAllUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllUsers(::grpc::ServerContext* /*context*/, const ::loboscontrol::Filters* /*request*/, ::loboscontrol::ListAllUsersReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListAllUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::loboscontrol::Filters* /*request*/, ::loboscontrol::ListAllUsersReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RmUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RmUser() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::loboscontrol::RmUserParams, ::google::protobuf::BoolValue>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::loboscontrol::RmUserParams* request, ::google::protobuf::BoolValue* response) { return this->RmUser(context, request, response); }));}
    void SetMessageAllocatorFor_RmUser(
        ::grpc::MessageAllocator< ::loboscontrol::RmUserParams, ::google::protobuf::BoolValue>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::loboscontrol::RmUserParams, ::google::protobuf::BoolValue>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RmUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::RmUserParams* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RmUser(
      ::grpc::CallbackServerContext* /*context*/, const ::loboscontrol::RmUserParams* /*request*/, ::google::protobuf::BoolValue* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_AddKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_AddKey() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::loboscontrol::User, ::loboscontrol::UserReply>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::loboscontrol::User* request, ::loboscontrol::UserReply* response) { return this->AddKey(context, request, response); }));}
    void SetMessageAllocatorFor_AddKey(
        ::grpc::MessageAllocator< ::loboscontrol::User, ::loboscontrol::UserReply>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::loboscontrol::User, ::loboscontrol::UserReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_AddKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddKey(
      ::grpc::CallbackServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RmKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RmKey() {
      ::grpc::Service::MarkMethodCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::loboscontrol::User, ::google::protobuf::BoolValue>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::loboscontrol::User* request, ::google::protobuf::BoolValue* response) { return this->RmKey(context, request, response); }));}
    void SetMessageAllocatorFor_RmKey(
        ::grpc::MessageAllocator< ::loboscontrol::User, ::google::protobuf::BoolValue>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(4);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::loboscontrol::User, ::google::protobuf::BoolValue>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RmKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RmKey(
      ::grpc::CallbackServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::google::protobuf::BoolValue* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_AddUser<WithCallbackMethod_ListAllUsers<WithCallbackMethod_RmUser<WithCallbackMethod_AddKey<WithCallbackMethod_RmKey<Service > > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddUser() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_ListAllUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_ListAllUsers() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_ListAllUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllUsers(::grpc::ServerContext* /*context*/, const ::loboscontrol::Filters* /*request*/, ::loboscontrol::ListAllUsersReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RmUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RmUser() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_RmUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::RmUserParams* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_AddKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_AddKey() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_AddKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RmKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RmKey() {
      ::grpc::Service::MarkMethodGeneric(4);
    }
    ~WithGenericMethod_RmKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddUser() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_ListAllUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_ListAllUsers() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_ListAllUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllUsers(::grpc::ServerContext* /*context*/, const ::loboscontrol::Filters* /*request*/, ::loboscontrol::ListAllUsersReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestListAllUsers(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RmUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RmUser() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_RmUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::RmUserParams* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRmUser(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_AddKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_AddKey() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_AddKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestAddKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RmKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RmKey() {
      ::grpc::Service::MarkMethodRaw(4);
    }
    ~WithRawMethod_RmKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRmKey(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(4, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddUser() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_ListAllUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_ListAllUsers() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->ListAllUsers(context, request, response); }));
    }
    ~WithRawCallbackMethod_ListAllUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status ListAllUsers(::grpc::ServerContext* /*context*/, const ::loboscontrol::Filters* /*request*/, ::loboscontrol::ListAllUsersReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* ListAllUsers(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RmUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RmUser() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RmUser(context, request, response); }));
    }
    ~WithRawCallbackMethod_RmUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::RmUserParams* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RmUser(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_AddKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_AddKey() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->AddKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_AddKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status AddKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* AddKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RmKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RmKey() {
      ::grpc::Service::MarkMethodRawCallback(4,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RmKey(context, request, response); }));
    }
    ~WithRawCallbackMethod_RmKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RmKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RmKey(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddUser() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::loboscontrol::User, ::loboscontrol::UserReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::loboscontrol::User, ::loboscontrol::UserReply>* streamer) {
                       return this->StreamedAddUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::loboscontrol::User,::loboscontrol::UserReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_ListAllUsers : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_ListAllUsers() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::loboscontrol::Filters, ::loboscontrol::ListAllUsersReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::loboscontrol::Filters, ::loboscontrol::ListAllUsersReply>* streamer) {
                       return this->StreamedListAllUsers(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_ListAllUsers() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status ListAllUsers(::grpc::ServerContext* /*context*/, const ::loboscontrol::Filters* /*request*/, ::loboscontrol::ListAllUsersReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedListAllUsers(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::loboscontrol::Filters,::loboscontrol::ListAllUsersReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RmUser : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RmUser() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::loboscontrol::RmUserParams, ::google::protobuf::BoolValue>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::loboscontrol::RmUserParams, ::google::protobuf::BoolValue>* streamer) {
                       return this->StreamedRmUser(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RmUser() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RmUser(::grpc::ServerContext* /*context*/, const ::loboscontrol::RmUserParams* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRmUser(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::loboscontrol::RmUserParams,::google::protobuf::BoolValue>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_AddKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_AddKey() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::loboscontrol::User, ::loboscontrol::UserReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::loboscontrol::User, ::loboscontrol::UserReply>* streamer) {
                       return this->StreamedAddKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_AddKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status AddKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::loboscontrol::UserReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedAddKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::loboscontrol::User,::loboscontrol::UserReply>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RmKey : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RmKey() {
      ::grpc::Service::MarkMethodStreamed(4,
        new ::grpc::internal::StreamedUnaryHandler<
          ::loboscontrol::User, ::google::protobuf::BoolValue>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::loboscontrol::User, ::google::protobuf::BoolValue>* streamer) {
                       return this->StreamedRmKey(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RmKey() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RmKey(::grpc::ServerContext* /*context*/, const ::loboscontrol::User* /*request*/, ::google::protobuf::BoolValue* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRmKey(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::loboscontrol::User,::google::protobuf::BoolValue>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_AddUser<WithStreamedUnaryMethod_ListAllUsers<WithStreamedUnaryMethod_RmUser<WithStreamedUnaryMethod_AddKey<WithStreamedUnaryMethod_RmKey<Service > > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_AddUser<WithStreamedUnaryMethod_ListAllUsers<WithStreamedUnaryMethod_RmUser<WithStreamedUnaryMethod_AddKey<WithStreamedUnaryMethod_RmKey<Service > > > > > StreamedService;
};

}  // namespace loboscontrol


#endif  // GRPC_loboscontrol_2eproto__INCLUDED
